# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='Name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
